const en = {
    links: {
        linkedinLink: `https://linkedin.com/in/confia-design/`,
        whatsLink: `https://api.whatsapp.com/send?phone=5511960687340&text=Hi!%20I'm%20interested%20in%20the%20services%2C%20could%20you%20give%20me%20a%20quote%3F`,
        instagramLink: `https://instagram.com/confiadesign`,
    },
    texts: {
        txt0: "home",
        txt1: "services",
        txt2: "portfolio",
        txt3: "contact",
        txt4: "Web Design",
        txt5: "Design and Navigability taken seriously. We develop your website to be intuitive and easy to navigate to direct your customer to take action.",
        txt6: "Web Development",
        txt7: `We develop systems to optimize and increase productivity, always thinking about your company's process and business model.`,
        txt8: "Graphic Design",
        txt9: `We will help you build your brand from ZERO and express it in the best possible way with your business and with your audience.`,
        txt10: "our retrospect",
        txt11: "projects delivered",
        txt12: "years of experience",
        txt13: "costumers",
        txt14: "monthly visits",
        txt15: "portfolio",
        txt16: '"The best proof of love is trust."',
        txt17: "by",
        txt18: "Joyce Brothers",
        txt19: "quickly access",
        txt20: "hire us",
        txt21: "home",
        txt22: "All rights reserved by Confia Design.",
        txt23: "Made with",
        txt24: "by",
        txt25: "services",
    },
};

export default en;
